AgStackRegistry/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from AgStackRegistry import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pwa.urls')),
    path(r'', include('api.urls')),
    path('chat/', include('chat.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path, include
from api.views import Register, Login, Logout, HomeView, ConfirmationPageView, ManageVoting, home_test, APIProductView, \
    ChatMessageView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.decorators.csrf import csrf_exempt

app_name = 'api'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('home/', HomeView.as_view(), name='home'),
    path('voting/', ManageVoting.as_view(), name='voting'),
    path(r'confirmation_page/', csrf_exempt(ConfirmationPageView.as_view()), name='confirmation_page'),
    path('login/', Login.as_view(), name='custom_login'),
    path('register/', Register.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='custom_logout'),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('search/', APIProductView.as_view({'get': 'list'}), name='search'),
    path('search-chat/', ChatMessageView.as_view({'get': 'list'}), name='search-chat'),
]


urlpatterns += staticfiles_urlpatterns()

templates/base_generic.html
<ul class="sidebar-nav d-none">
{% load pwa %}
{% progressive_web_app_meta %}

    {% if user.is_authenticated %}
        <li class="d-none"><a href="{% url 'logout' %}?next={{ request.path }}"></a></li>
    {% else %}
        <li><a href="{% url 'api:home' %}"></a></li>
    {% endif %}
</ul>

templates/confirmation_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% include "header.html" %}
</head>
<body>
    {% include 'navbar.html' %}

    <div class="container">
        <div class="row">
            {% if status %}
                <h6 class="alert-success mx-auto d-flex justify-content-center p-3">{{ status }}</h6>
            {% endif %}
        </div>

        <div class="row">

            <div class="col mx-auto">
                {% if product.logo %}
                    <img class="w-100" src="{{ product.logo }}">
                {% else %}
                    <img class="" alt="sample">
                {% endif %}
            </div>
            <div class="col offset-1">
                <form action="{% url 'api:confirmation_page' %}" method="post">
                    {% csrf_token %}
                    <input class="d-none" type="text" name="product_id" value="{{ product.id }}"/>

                    <p>
                        <h3>{{ product.name }}</h3>
                    </p><br/>

                    <p>{{ product.about }}</p>

                    <p>
                        {% if subscription.status %}
                            <div>
                                <strong>subscription: </strong>
                                <div class="badge badge-success">active </div>
                            </div>
                        {% else %}
                            <div>
                                <strong>subscription: </strong>
                                <div class="badge badge-danger">inactive </div>
                            </div>
                        {% endif %}
                    </p>

                    <p><strong>token: </strong>{{ subscription.token }}</p><br/>

                    <p>
                        {% if subscription.status %}
                            <input class="btn btn-lg btn-danger" type="submit" name="unsubscribe" value="Confirm unsubscription"/>
                        {% else %}
                            <input class="btn btn-lg btn-success" type="submit" name="subscribe" value="Confirm subscription"/>
                        {% endif %}

                    </p>
                </form>
            </div>
        </div>
    </div>

</body>
</html>

templates/header.html
{% load static %}
<meta charset="utf-8">
<meta charset="UTF-8">
<title>{{ title }}</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link type="text/css" rel="stylesheet" href="{% static "styles.css" %}" media="screen,projection" />
{% load pwa %}
{% progressive_web_app_meta %}
{#{% pwa_meta_data %}#}
{#{% pwa_meta_script %}#}

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% include "header.html" %}
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% if error %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% elif success %}
            <div class="alert alert-success">
                {{ success }}
            </div>
        {% endif %}
        <div class="row">
            <div class="col-2 m-4">
                <input id="searchbar" type="text" placeholder="Search..">
            </div>
            <div class="col-2 m-4">
                <input id="searchbarChat" type="text" placeholder="Search Chats..">
            </div>
        </div>
        <table id="customTable" class="table table-striped w-75 mx-auto">
          <thead>
{#            <tr>#}
{#              <th scope="col">ID</th>#}
              <th scope="col">Topic</th>
              <th scope="col">Logo</th>
              <th scope="col">Subscription</th>
              <th scope="col">Invite</th>
{#            </tr>#}
          </thead>
          <tbody>
            {% for obj in api_products %}
                <tr>
                    <form action="{% url 'api:confirmation_page' %}" method="get">
                        {% csrf_token %}
{#                        <td>{{ obj.id }}</td>#}
                        <input class='d-none' type='text' name='product_name' value='{{ obj.name }}'/>
                        <td>{{ obj.name }}</td>
                        <td>
                            {% if obj.logo %}
                                <img class="row-img" src="{{ obj.logo }}">
                            {% else %}
                                <img class="card-img-top" alt="sample">
                            {% endif %}
                        </td>
                        <td>
                            <input class="btn btn-sm btn-success" type="submit"
                              name="subscribe" value="subscribe"/>
                            <input class="btn btn-sm btn-danger" type="submit"
                              name="unsubscribe" value="unsubscribe"/>
                            <input class="btn btn-sm btn-dark" type="submit"
                              name="chat" value="chat"/>
                        </td>
                        <td>
                            <input type='text' name='invite_email' value=''>
                            <input class="btn btn-sm btn-primary" type="submit"
                              name="invite" value="invite"/>
                        </td>
                    </form>
                </tr>
            {% endfor %}

          </tbody>
        </table>
    </div>

{% block content %}
{% endblock content %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
{% block javascript %}
{% endblock javascript %}

</body>
<script>

    var input = document.getElementById("searchbar");
    input.addEventListener("keydown", function (e) {
        if (e.key === "Enter") {
          search(e);
        }
    });

    function search(e) {
        var text = e.target.value;

        if (text != ''){
            text = "search?search="+text;
            var serializedData = $(this).serialize();

            $.ajax({
                type: 'GET',
                url: "{% url 'api:search' %}",
                data: {
                    search: text,
                },
                success: function (response) {
                    {#filtering based on the results#}
                    const table = document.getElementById('customTable');
                    table.classList.add("table-striped");

                    var tbodyRef = document.getElementById('customTable').getElementsByTagName('tbody')[0];

                    {#$("#customTable tbody").closest('tr').nextAll();#}
                    $("#customTable > tbody"). empty();
                    debugger
                    for(i in response) {

                        var row = tbodyRef.insertRow();

                        {#var row = table.insertRow(-1);#}

                        var cell1 = row.insertCell(0);
                        var cell2 = row.insertCell(1);
                        var cell3 = row.insertCell(2);
                        var cell4 = row.insertCell(3);

                        cell1.innerHTML = "<input class='d-none' type='text' name='product_name' value='"+response[i].name+"'onclick='goToConfirmationPage()'/>"+response[i].name;
                        if (response[i].logo) {
                            cell2.innerHTML = " <img class='row-img' src='"+response[i].logo+"'>"
                        } else {
                            cell2.innerHTML = " <img class='card-img-top' alt='sample'>"
                        }
                        var prod_name = response[i].name;
                        cell3.innerHTML = "<input class='btn btn-sm btn-success' type='submit' name='subscribe' value='subscribe' onclick='goToConfirmationPage(`subscribe`,`"+response[i].name+"`)'/>"+
                                          "<input class='btn btn-sm btn-danger' type='submit' name='unsubscribe' value='unsubscribe' onclick='goToConfirmationPage(`unsubscribe`,`"+response[i].name+"`)'/>"+
                                          "<input class='btn btn-sm btn-dark' type='submit' name='chat' value='chat' onclick='goToConfirmationPage(`chat`,`"+response[i].name+"`)'/>";
                        cell4.innerHTML = "<input type='text' id=`"+response[i].name+"` name='invite_email' value=''><input class='btn btn-sm btn-primary' type='submit' name='invite' value='invite' onclick='goToConfirmationPage(`invite`,`"+response[i].name+"`)'/>";
                    }

                },
                error: function (response) {
                    // alert the error if any error occured
                    alert(response["responseJSON"]["error"]);
                }
            })
        }

    }

</script>
<script>

    var input = document.getElementById("searchbarChat");
    input.addEventListener("keydown", function (e) {
        if (e.key === "Enter") {
          searchChat(e);
        }
    });

    const arrayContainsObject = (array, object) => {
      return array.some(item => Object.keys(item).every(key => item[key] === object[key]))
    }

    function searchChat(e) {
        var text = e.target.value;

        if (text != ''){
            text = "search-chat?description="+text;
            var serializedData = $(this).serialize();

            $.ajax({
                type: 'GET',
                url: "{% url 'api:search-chat' %}",
                data: {
                    search: text,
                },
                success: function (response) {
                    {#filtering based on the results#}
                    const table = document.getElementById('customTable');
                    table.classList.add("table-striped");

                    var tbodyRef = document.getElementById('customTable').getElementsByTagName('tbody')[0];

                    {#$("#customTable tbody").closest('tr').nextAll();#}
                    $("#customTable > tbody"). empty();

                    debugger
                    var arr = [];
                    for(i in response) {
                        if (!arrayContainsObject(arr, response[i]['topic'])){
                            arr.push(response[i]['topic']);
                        }
                    }

                    debugger
                    for(i in arr) {

                        var row = tbodyRef.insertRow();

                        {#var row = table.insertRow(-1);#}

                        var cell1 = row.insertCell(0);
                        var cell2 = row.insertCell(1);
                        var cell3 = row.insertCell(2);
                        var cell4 = row.insertCell(3);

                        cell1.innerHTML = "<input class='d-none' type='text' name='product_name' value='"+arr[i].name+"'onclick='goToConfirmationPage()'/>"+arr[i].name;
                        if (arr[i].logo) {
                            cell2.innerHTML = " <img class='row-img' src='"+arr[i].logo+"'>"
                        } else {
                            cell2.innerHTML = " <img class='card-img-top' alt='sample'>"
                        }
                        var prod_name = arr[i].name;
                        cell3.innerHTML = "<input class='btn btn-sm btn-success' type='submit' name='subscribe' value='subscribe' onclick='goToConfirmationPage(`subscribe`,`"+arr[i].name+"`)'/>"+
                                          "<input class='btn btn-sm btn-danger' type='submit' name='unsubscribe' value='unsubscribe' onclick='goToConfirmationPage(`unsubscribe`,`"+arr[i].name+"`)'/>"+
                                          "<input class='btn btn-sm btn-dark' type='submit' name='chat' value='chat' onclick='goToConfirmationPage(`chat`,`"+arr[i].name+"`)'/>";
                        cell4.innerHTML = "<input type='text' id=`"+arr[i].name+"` name='invite_email' value=''><input class='btn btn-sm btn-primary' type='submit' name='invite' value='invite' onclick='goToConfirmationPage(`invite`,`"+arr[i].name+"`)'/>";
                    }

                },
                error: function (response) {
                    // alert the error if any error occured
                    alert(response["responseJSON"]["error"]);
                }
            })
        }

    }

</script>
<script>
    function goToConfirmationPage(e, name) {
        // e is the functionality to perform in backend
        // name is the api product name for which the functionality needs to be performed
        debugger
        {#default would be subscribe#}
        var text = e == 'invite' ? {invite: 'invite', invite_email: document.getElementById(name)} : e == 'unsubscribe' ? {unsubscribe: 'unsubscribe'} : e == 'chat' ? {chat: 'chat'} : {subscribe: 'subscribe'}
        text['product_name'] = name
        $.ajax({
            type: 'GET',
            url: "{% url 'api:confirmation_page' %}",
            data: text,
            success: function (data, textStatus) {
                debugger
                if(e == 'chat') {
                    window.location.href = '/confirmation_page/?product_name='+name+'&chat=chat&invite_email='
                } else {
                    window.location.href = '/confirmation_page/?product_name='+name
                }

            }
        })
    }
</script>
</html>



{#a big problem in this code is there are 2 flows to complete the backend, one via js and the other via html, js is prefered through out the file#}

templates/navbar.html
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3"
         style="background-color:#34495e; color:antiquewhite;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'api:home' %}"><i class="fa fa-home" aria-hidden="true"></i>Home</a>
            <a href="{% url 'api:home' %}" class="btn btn-dark btn-sm">
                Pub Sub
            </a>
            <a href="#" class="ml-2 btn btn-dark btn-sm">
                Weather System
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav nav nav-pills" style="margin-left:auto;">
                    <li class="nav-item">
                        <a class="nav-link text-light" href="{% url 'api:custom_logout' %}?next={{ request.path }}">
                            Hi, {{ user.email }}
                            <i class="fa fa-sign-out" aria-hidden="true"></i> &nbsp
                            Log Out
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/register-new.html
    <div class="container">

    <form class="well form-horizontal" action=" " method="post"  id="contact_form">
<fieldset>

<!-- Form Name -->
<legend><center><h2><b>Registration Form</b></h2></center></legend><br>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">First Name</label>
  <div class="col-md-4 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input  name="first_name" placeholder="First Name" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Last Name</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="last_name" placeholder="Last Name" class="form-control"  type="text">
    </div>
  </div>
</div>

  <div class="form-group">
  <label class="col-md-4 control-label">Department / Office</label>
    <div class="col-md-4 selectContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
    <select name="department" class="form-control selectpicker">
      <option value="">Select your Department/Office</option>
      <option>Department of Engineering</option>
      <option>Department of Agriculture</option>
      <option >Accounting Office</option>
      <option >Tresurer's Office</option>
      <option >MPDC</option>
      <option >MCTC</option>
      <option >MCR</option>
      <option >Mayor's Office</option>
      <option >Tourism Office</option>
    </select>
  </div>
</div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Username</label>
  <div class="col-md-4 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input  name="user_name" placeholder="Username" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Password</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="user_password" placeholder="Password" class="form-control"  type="password">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Confirm Password</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="confirm_password" placeholder="Confirm Password" class="form-control"  type="password">
    </div>
  </div>
</div>

<!-- Text input-->
       <div class="form-group">
  <label class="col-md-4 control-label">E-Mail</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
  <input name="email" placeholder="E-Mail Address" class="form-control"  type="text">
    </div>
  </div>
</div>


<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Contact No.</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
  <input name="contact_no" placeholder="(639)" class="form-control" type="text">
    </div>
  </div>
</div>

<!-- Select Basic -->

<!-- Success message -->
<div class="alert alert-success" role="alert" id="success_message">Success <i class="glyphicon glyphicon-thumbs-up"></i> Success!.</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label"></label>
  <div class="col-md-4"><br>
    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<button type="submit" class="btn btn-warning" >&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspSUBMIT <span class="glyphicon glyphicon-send"></span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</button>
  </div>
</div>

</fieldset>
</form>
</div>
    </div><!-- /.container -->

templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en" background-img>

    <head>
        <title>Register</title>
        {% include "header.html" %}
        <link href="dist/css/component-custom-switch.css" rel="stylesheet">
    </head>
    <body class="back">
        {% include "base_generic.html" %}

        {% block content %}

        <div class="container">

            <div class="d-flex justify-content-center logo-box">
                <img src="{% static 'logo.png' %}">
            </div>
            <h3 class="d-flex justify-content-center">Register</h3>
            <div class="jumbotron m-5">
                {% if form.errors %}
                    <h6 class="alert-danger col-4 p-2 offset-4">Your username and password didn't match. Please try again.</h6>
                {% endif %}
                {% if errors %}
                    <h6 class="alert-danger col-4 p-2 offset-4">{{ errors }}</h6>
                {% endif %}
                {% if success %}
                    <h6 class="alert-success col-4 p-2 offset-4">{{ success }}</h6>
                {% endif %}
                <form class="" method="post" action="{% url 'api:register' %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-4 offset-2">

                              <div class="form-group">
                                <label for="exampleInputUsername">Username/Email{{ " " }}<span class="required">*</span></label>
                                <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
                              </div>
{#                              <div class="form-group">#}
{#                                <label for="exampleInputEmail1">Email address</label>#}
{#                                <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email">#}
{#                              </div>#}
                              <div class="form-group">
                                <label for="exampleInputPhonenumber">Phone number{{ " " }}<span class="required">*</span></label>
                                <input type="text" class="form-control" id="phone" name="phone" placeholder="Enter phone">
                              </div>
                              <div class="form-group">
                                <div class="form-check form-switch pl-0" >
                                  <label class="form-check-label" for="flexSwitchCheckDefault">Discoverable{{ " " }}<span class="required">*</span></label>
                                  <input class="form-check-input check-focus ml-3" style="height: 2em; width: 3em;" type="checkbox"
                                  id="discoverable" name="discoverable" placeholder="Discoverable">
                                </div>
                              </div>

                        </div>

                        <div class="col-4">
                            <div class="form-group">
                               <label>Usage{{ " " }}<span class="required">*</span></label>
                               <select class="form-control" id="usage" name="usage" required>
                                  <option value="commercial">commercial</option>
                                     <option value="research" data-value='research'>research</option>
                                     <option value="educational" data-value='educational'>educational</option>
                                     <option value="government" data-value='government'>government</option>
                               </select>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Password{{ " " }}<span class="required">*</span></label>
                                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                            </div>
                            <div class="mt-5">
                              <a href="{% url 'api:custom_login' %}" class="mr-4">Already have an account?</a>
                              <button type="submit" class="btn btn-danger">Create</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        {# Assumes you setup the password_reset view in your URLconf #}
{#        <p><a href="{% url 'password_reset' %}">Lost password?</a></p>#}

    {% endblock %}
    </body>

<script>
$(".checkbox").Sswitch({
  onSwitchChange:function() {

   console.log('aanish')
  }
});

</script>
</html>

templates/test.html
<!DOCTYPE html>
<html>
<head>
    <title>AutoComplete</title>
    <script src=
"https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js">
    </script>

    <script src=
"https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js">
    </script>

    <link href=
"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css"
        rel="stylesheet" type="text/css" />
</head>
<body>
    <h1>Welcome to GFG</h1>
    <input type="text" id="tags">
    <script>
  $( function() {
    var availableTags = [
        {% for language in languages %}
            "{{language.name}}",
        {% endfor %}
    ];
    $( "#tags" ).autocomplete({
      source: availableTags
    });
  } );
  </script>

</body>
</html>